### ISSUE TITLE
Installing xapers on Ubuntu 16.10

### ISSUE THREAD

**Issue by theGreatWhiteShark** [pazz/xapers#2]
Hey, 

I would love to try the package. But regardless how I try to install it (via apt, pip or setup.py install in the repository), I always get the same error message:

> ~/git/xapers $ python

> Python 2.7.12+ (default, Sep 17 2016, 12:08:02) 
> [GCC 6.2.0 20160914] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import xapers
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python2.7/dist-packages/xapers/__init__.py", line 21, in <module>
>     from database import Database
>   File "/usr/local/lib/python2.7/dist-packages/xapers/database.py", line 26, in <module>
>     from documents import Documents, Document
>   File "/usr/local/lib/python2.7/dist-packages/xapers/documents.py", line 27, in <module>
>     from bibtex import Bibtex
>   File "/usr/local/lib/python2.7/dist-packages/xapers/bibtex.py", line 6, in <module>
>     from pybtex.core import Entry, Person
> ImportError: No module named core

All the dependencies are already installed as well.

Do you have any suggestions how to solve this issue? (Hint: I'm not a Python expert)

Cheers,
Philipp

**Comment by nbeaver** [comment]
The pybtex developers broke backward compatibility several years ago:

https://bitbucket.org/pybtex-devs/pybtex/commits/7de402cafd19219f0fcb7da7d58fbe04c192372f

I'll see if I can submit a pull request, but in the meantime the patch is trivial:

    diff --git a/lib/xapers/bibtex.py b/lib/xapers/bibtex.py
    index 3dda91f..a66038a 100644
    --- a/lib/xapers/bibtex.py
    +++ b/lib/xapers/bibtex.py
    @@ -3,7 +3,7 @@ import sys
     import io
     import json
     import pybtex
    -from pybtex.core import Entry, Person
    +from pybtex.database import Entry, Person
     from pybtex.bibtex.utils import split_name_list
     from pybtex.database.input import bibtex as inparser
     from pybtex.database.output import bibtex as outparser

**Comment by pazz** [comment]
I should say that this is not my project. I do not maintain nor use it at this
moment. The original seems unavailable and unmaintained though.

**Comment by theGreatWhiteShark** [comment]
Ah, indeed. I didn't thought this repo to be a fork. 

The original one is working just fine https://github.com/jrollins/xapers
